import {
  ArrowLeft,
  ShieldAlert
} from "lucide-react";

import {
  useEffect,
  useState
} from "react";

import {
  useNavigate,
  useParams
} from "react-router-dom";

import client from "../api/client";

import RiskBadge
  from "../components/common/RiskBadge";

import RiskBreakdown
  from "../components/wallet/RiskBreakdown";


function AlertDetail() {

  const {
    id
  } = useParams();

  const navigate =
    useNavigate();

  const [alert, setAlert] =
    useState(null);

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState("");


  useEffect(() => {

    const loadAlert =
      async () => {

        setLoading(true);
        setError("");

        try {

          const response =
            await client.get(
              `/alerts/${id}`
            );

          setAlert(
            response.alert || null
          );

        } catch (error) {

          setError(
            error.message ||
            "Unable to load alert."
          );

        } finally {

          setLoading(false);

        }

      };


    loadAlert();

  }, [id]);


  if (loading) {

    return (
      <div className="card p-10 text-center">

        <ShieldAlert
          size={40}
          className="mx-auto text-gray-600"
        />

        <h2 className="text-xl font-semibold mt-4">
          Loading alert...
        </h2>

      </div>
    );

  }


  if (error || !alert) {

    return (
      <div className="card p-10 text-center">

        <ShieldAlert
          size={40}
          className="mx-auto text-gray-600"
        />

        <h2 className="text-xl font-semibold mt-4">
          Alert not found
        </h2>

        <p className="text-gray-500 mt-2">
          {error ||
            "The requested alert could not be found."}
        </p>

        <button
          onClick={() =>
            navigate("/alerts")
          }
          className="
            mt-5
            px-4 py-2
            bg-orange-500
            text-black
            rounded-lg
          "
        >
          Back to Alerts
        </button>

      </div>
    );

  }


  /*
   * Backend risk_score is stored from 0 to 100.
   *
   * RiskBadge expects a value from 0 to 1.
   */

  const riskScore =
    Number(
      alert.risk_score
    ) || 0;

  const normalizedRisk =
    Math.min(
      1,
      Math.max(
        0,
        riskScore / 100
      )
    );


  const confidence =
    Number(
      alert.confidence
    ) || 0;


  /*
   * Evidence generated by the
   * analysis service.
   */

  const evidence =
    alert.evidence &&
    typeof alert.evidence === "object"
      ? alert.evidence
      : {};


  const evidenceItems =
    Array.isArray(
      evidence.factors
    )
      ? evidence.factors
      : [];


  /*
   * Convert evidence into readable flags.
   */

  const flags =
    evidenceItems
      .map(
        (item) =>
          item.label ||
          item.feature
      )
      .filter(Boolean);


  /*
   * Display risk breakdown.
   *
   * These percentages represent the
   * overall alert risk because the
   * stored alert contains one final
   * risk score.
   */

  const breakdown = [
    {
      name:
        "Transaction Frequency",

      value:
        normalizedRisk * 100,

      description:
        "Transaction activity associated with this wallet."
    },

    {
      name:
        "Transaction Volume",

      value:
        normalizedRisk * 100,

      description:
        "Value transferred by the wallet."
    },

    {
      name:
        "Network Complexity",

      value:
        normalizedRisk * 100,

      description:
        "Complexity of connected wallet relationships."
    }
  ];


  return (
    <div className="space-y-6">

      <button
        onClick={() =>
          navigate("/alerts")
        }
        className="
          flex
          items-center
          gap-2
          text-gray-400
          hover:text-white
        "
      >

        <ArrowLeft
          size={18}
        />

        Back to Alerts

      </button>


      <div>

        <p className="text-orange-400 text-xs">
          SECURITY ALERT
        </p>

        <h1 className="text-3xl font-bold mt-2">
          Suspicious Wallet Activity
        </h1>

      </div>


      <div className="card p-6">

        <div className="
          flex
          flex-col
          md:flex-row
          md:items-center
          justify-between
          gap-4
        ">

          <div>

            <p className="text-gray-500 text-sm">
              Wallet Address
            </p>

            <p className="
              wallet-address
              text-orange-400
              mt-2
            ">
              {alert.wallet_address ||
                "-"}
            </p>

          </div>


          <RiskBadge
            score={normalizedRisk}
          />

        </div>

      </div>


      <div className="
        grid
        grid-cols-1
        xl:grid-cols-2
        gap-6
      ">


        <div className="card p-6">

          <h2 className="font-semibold text-lg">
            Alert Explanation
          </h2>


          <p className="text-gray-500 text-sm mt-2">
            {alert.reason ||
              "Behavioral anomaly detected."}
          </p>


          <div className="mt-6">

            <RiskBreakdown
              breakdown={breakdown}
            />

          </div>

        </div>


        <div className="card p-6">

          <h2 className="font-semibold text-lg">
            Detection Information
          </h2>


          <div className="space-y-4 mt-6">


            <div>

              <p className="text-xs text-gray-500">
                Status
              </p>

              <p className="text-red-400 mt-1">
                {alert.severity
                  ? alert.severity
                      .charAt(0)
                      .toUpperCase() +
                    alert.severity.slice(1)
                  : "Active"}
              </p>

            </div>


            <div>

              <p className="text-xs text-gray-500">
                Risk Score
              </p>

              <p className="text-xl font-bold mt-1">
                {riskScore.toFixed(1)}
              </p>

            </div>


            <div>

              <p className="text-xs text-gray-500">
                Confidence
              </p>

              <p className="text-xl font-bold mt-1">
                {confidence.toFixed(1)}%
              </p>

            </div>


            <div>

              <p className="text-xs text-gray-500">
                Severity
              </p>

              <p className="
                mt-1
                capitalize
                text-orange-400
              ">
                {alert.severity ||
                  "-"}
              </p>

            </div>


            <div>

              <p className="text-xs text-gray-500">
                Flags
              </p>


              <div className="
                flex
                flex-wrap
                gap-2
                mt-2
              ">

                {flags.length > 0 ? (

                  flags.map(
                    (flag, index) => (

                      <span
                        key={`${flag}-${index}`}
                        className="
                          px-2
                          py-1
                          bg-gray-800
                          rounded
                          text-xs
                          text-gray-400
                        "
                      >
                        {flag}
                      </span>

                    )
                  )

                ) : (

                  <span className="
                    text-gray-600
                    text-sm
                  ">
                    No additional flags
                  </span>

                )}

              </div>

            </div>


            {alert.transaction_id && (

              <div>

                <p className="text-xs text-gray-500">
                  Transaction ID
                </p>

                <p className="
                  mt-1
                  text-gray-300
                ">
                  {alert.transaction_id}
                </p>

              </div>

            )}


            <div>

              <p className="text-xs text-gray-500">
                Created
              </p>

              <p className="
                mt-1
                text-gray-300
              ">
                {alert.created_at
                  ? new Date(
                      alert.created_at
                    ).toLocaleString()
                  : "-"}
              </p>

            </div>

          </div>

        </div>

      </div>

    </div>
  );
}


export default AlertDetail;